import express from "express";
import path from "path";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";
import { createServer as createViteServer } from "vite";

// Load environment variables
dotenv.config();

const app = express();
const PORT = 3000;

// Initialize Gemini SDK with telemetry headers as required by skills
const apiKey = process.env.GEMINI_API_KEY;
let ai: GoogleGenAI | null = null;

if (apiKey) {
  ai = new GoogleGenAI({
    apiKey: apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
} else {
  console.warn("WARNING: GEMINI_API_KEY environment variable is not set. Chatbot will run in offline demo mode.");
}

app.use(express.json());

// API route for chatbot conversation
app.post("/api/chat", async (req, res) => {
  try {
    const { message, history } = req.body;
    if (!message) {
      return res.status(400).json({ error: "Message is required." });
    }

    if (!ai) {
      // Return a friendly fallback if API key is not configured
      return res.json({
        text: `[Offline Mode] Thank you for contacting PESA Consulting Group. Our new Service Division is designed to support business startups, investment projects, consulting, internal controls, financial/inventory audits, and management assistance under a rigorous execution pipeline. To get in touch, please email us at info@pesagroup.org, or call our US office at +1 (682) 424-5857 or DRC office at +243 821368004. How else can we help you explore our services in Real Estate, Strategy Consulting, Private Jet sales, Visa Services, Mining, or our new outsourcing and audit division?`,
        isDemo: true
      });
    }

    const systemInstruction = `You are the official Pesa Group AI Ambassador, representing PESA Consulting Group LLC (Pesa Group). Your role is to provide elite, professional, and accurate information to clients, investors, and partners who visit our digital headquarters.

PESA stands for: Purpose, Expansion, Structure, Assembly.
Our primary motto is: "WE PROVIDE REAL SOLUTIONS FOR REAL PEOPLE."

Maintain an extremely professional, sophisticated, yet warm and approachable tone. Align all answers strictly with the following verified company facts:

### NEW SERVICE DIVISION LAUNCH (PESA Service Division):
- We are launching a new service division offering comprehensive support: business startups, investment projects, investment consulting, implementation of internal controls, financial or inventory audits, and management assistance (allowing investors to outsource part of their operations, obtain specific administrative documents, or launch a business activity).
- Professional Core Values: Built strictly on quality work, adherence to deadlines, and absolute rigor in task execution. Personal affinities, friendships, and favoritism must be set aside to guarantee world-class deliverables.
- Prioritizing Long-Term Markets: Our strategic focus is on securing long-term contracts—specifically those lasting at least five (5) years.

### LEAN LAUNCH-PHASE ORGANIZATION & OUTSOURCING:
- PESA operates with a lean startup structure, relying heavily on professional outsourcing to maximize execution speed and efficiency.
- USA Team: Manages the Presidency, technological infrastructure, and part of the financial operations. Handles day-to-day activities, corporate strategy, field marketing, and market development/acquisition.
- Kinshasa Team: Handles finance & audit, as well as marketing & strategy. Works in close synergy with the USA team.
  * Finance Team: Synergizes with the USA team to tailor offers to secured markets.
  * Audit Team: Manages all control and audit contracts, utilizing qualified subcontractors to execute the physical tasks.
  * Marketing & Strategy Team: Focuses on securing high-impact contracts to drive growth.

### CONTRACT FINANCING & PAYMENTS:
- Two Financing Methods Available:
  1. Pre-financing by PESA: Strictly requires the signing of a contract or Memorandum of Understanding (MOU) between the parties first.
  2. Financing by the Client: Structured either in installments or in full.
- Strict Cash Ban Policy: No agent or representative is authorized to accept cash payments under any circumstances, regardless of rank or position. All payments must be made exclusively via secure bank wire transfer. Official bank details are provided directly to the client immediately upon the signing of the contract or MOU.

### AGENT COMPENSATION & DIVIDENDS:
- Securing a Contract: Once approved by management and signed by both parties, the exact amount due is communicated to the securing agent.
- Account Management: The securing agent manages that specific client account and receives a share of the dividends generated by the contract.
- Dividend Distribution: Distributed according to a pre-established senior management formula (percentage of the company's profit margin based on contract value ranges).
- Long-Term Remuneration: Because we prioritize 5+ year contracts, the securing agent receives stable monthly remuneration until the contract expires. Terms are negotiated between the agent and senior management based on predefined ranges.

### ACTIVITY REPORTING:
- Activity Reports: Each agent is strictly required to submit weekly/monthly activity reports to facilitate management oversight and performance monitoring. Precise frequency rules will be detailed in the upcoming procedures manual.

### Leadership Team:
- Camy Likobe: President & Chief Executive Officer (CEO). An accomplished corporate leader with over a decade of financial and market brokerage experience (formerly at Branch Bank & Trust, TD Ameritrade, and Competitive Edge Realty as an independent elite Realtor).
- Charles Adekola: Vice President. 10+ years in the loan and lending industry, starting his career at Lender Express.
- Carole Boboy: Chief Operations Officer (COO).
- Laetitia Kalala: Chief Financial Officer (CFO).

### Global Offices:
- United States: Dallas, Texas. Phone: +1 682-424-5857.
- Democratic Republic of Congo (DRC): Kinshasa. Phone: +243 821368004.
- General Email: info@pesagroup.org

### Core Business Pillars & Services:
1. Strategy Consulting & New Service Division:
   - Corporate growth, capital structuring, EB-5 visa investment advisory, business startup support, outsourcing, and audits.
   - EB-5 Track Record: 300+ investors from 30+ countries across 6 sponsored funds, 100% approval rate.
2. Real Estate Brokerage:
   - Elite residential and commercial property acquisition and sales led by Camy Likobe.
3. Land & Construction:
   - Land opportunities, site selection, zoning, permitting, environmental due diligence.
4. Visa Services (PESA Education):
   - Gateway for US student visas and international study abroad programs.
5. Private Jet Sourcing & Acquisition:
   - Executive private jets through an off-market global broker network with technical engineer audits.
6. Mining & Critical Minerals:
   - Ethical, reliable supplier of premium mining products and strategic minerals.

Guidelines for your responses:
- Keep answers concise, informative, and beautifully structured. Use professional bullet points.
- Boldly communicate the strict cash ban policy (Bank transfer only) and PESA's commitment to rigor and 5-year contracts.
- If asked about compensation, describe the dividend share and negotiated monthly remuneration for the agent.
- Never write code, terminal logs, or internal system terms. Keep it fully customer-facing and elegant.`;

    // Reconstruct conversation history for Gemini. 
    // Format required: [{ role: 'user' | 'model', parts: [{ text: string }] }]
    const contents: any[] = [];
    if (history && Array.isArray(history)) {
      history.forEach((h: any) => {
        contents.push({
          role: h.role === "assistant" ? "model" : "user",
          parts: [{ text: h.content }],
        });
      });
    }

    // Append the current message
    contents.push({
      role: "user",
      parts: [{ text: message }],
    });

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: contents,
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.7,
      },
    });

    return res.json({ text: response.text });
  } catch (error: any) {
    console.error("Gemini API Error in backend:", error);
    return res.status(500).json({
      error: "Our AI Ambassador is currently reviewing other portfolios. Please try again shortly or contact our executives directly at info@pesagroup.org.",
      details: error.message,
    });
  }
});

// Setup Vite Dev Server / Static Asset Serving
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    console.log("Starting server in DEVELOPMENT mode with Vite Middleware...");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    console.log("Starting server in PRODUCTION mode...");
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Pesa Group Redesign Server running on http://localhost:${PORT}`);
  });
}

startServer();
